addons:
  apt:
    packages:
        - libfreetype6-dev
        - libglew-dev
        - libglfw3-dev
dist: trusty
group: beta
language: python
python:
  - "3.5"
script: python setup.py && python setup.py test
sudo: false
