language: python
python:
  - "3.5"
matrix:
    include:
        - os: linux
          dist: trusty
          group: beta
          sudo: false
          env:
            - CC=gcc ASANLIB=libasan.so.0 ASAN_ARG=--asan
          addons:
            apt:
              packages:
                - libfreetype6-dev
                - libglew-dev
                - libxi-dev 
                - libxrandr-dev 
                - libxinerama-dev 
                - libxcursor-dev
                - clang

        - os: linux
          dist: trusty
          group: beta
          sudo: false
          env:
            - CC=clang
            - RUN_FLAKE=1
          addons:
            apt:
              packages:
                - libfreetype6-dev
                - libglew-dev
                - libxi-dev 
                - libxrandr-dev 
                - libxinerama-dev 
                - libxcursor-dev
                - clang
    exclude:
        - os: linux
          env:

install:
    - pip install flake8
    - wget -O glfw-3.2.1.zip https://github.com/glfw/glfw/archive/3.2.1.zip
    - unzip glfw-3.2.1.zip
    - cd glfw-3.2.1
    - cmake -DBUILD_SHARED_LIBS=ON -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF -DCMAKE_INSTALL_PREFIX=$HOME/glfw
    - make
    - make install
    - cd ..
    - pkg-config --cflags glfw3
env:
    global:
        - PKG_CONFIG_PATH=$HOME/glfw/lib/pkgconfig 
        - LD_LIBRARY_PATH=$HOME/glfw/lib 
        - ASAN_OPTIONS=leak_check_at_exit=0 
before_script:
    - python setup.py build --debug $ASAN_ARG
script: 
    - LD_PRELOAD=$ASANLIB python setup.py test
    - if [[ "$RUN_FLAKE" == "1" ]]; then flake8 .; fi
