matrix:
    fast_finish: true
    include:
        - os: linux
          dist: trusty
          group: beta
          sudo: false
          env:
            - CC=gcc ASANLIB=libasan.so.0 ASAN_ARG=--asan
          language: python
          python: "3.5"
          addons:
            apt:
              packages:
                - libfreetype6-dev
                - libglew-dev
                - libxi-dev 
                - libxrandr-dev 
                - libxinerama-dev 
                - libxcursor-dev

        - os: linux
          dist: trusty
          group: beta
          sudo: false
          env:
            - CC=clang
            - RUN_FLAKE=1
          language: python
          python: "3.5"
          addons:
            apt:
              packages:
                - libfreetype6-dev
                - libglew-dev
                - libxi-dev 
                - libxrandr-dev 
                - libxinerama-dev 
                - libxcursor-dev
                - clang
        - os: osx
          language: generic
          before_install:
              - brew update
                # We dont install fontconfig as installing it is very slow and we dont need it to run the test suite anyway
              - brew install python3 freetype glew glfw

install: |
    if [[ "$RUN_FLAKE" == "1" ]]; then pip install flake8; fi
    if [[ "$TRAVIS_OS_NAME" == 'osx' ]]; then
        python3 -m venv venv;
        source venv/bin/activate;
        python3 -m sysconfig
    else
        wget -O glfw-3.2.1.zip https://github.com/glfw/glfw/archive/3.2.1.zip
        unzip glfw-3.2.1.zip
        cd glfw-3.2.1
        cmake -DBUILD_SHARED_LIBS=ON -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF -DCMAKE_INSTALL_PREFIX=$HOME/glfw
        make
        make install
        cd ..
    fi
    pkg-config --cflags glfw3

env:
    global:
        - PKG_CONFIG_PATH=$HOME/glfw/lib/pkgconfig 
        - LD_LIBRARY_PATH=$HOME/glfw/lib 
        - ASAN_OPTIONS=leak_check_at_exit=0 
before_script:
    - python setup.py build --debug $ASAN_ARG;
script: 
    - LD_PRELOAD=$ASANLIB python setup.py test
    - if [[ "$RUN_FLAKE" == "1" ]]; then flake8 --count .; fi
