version: 2
jobs:
  linux-system-python:
    docker:
        - image: kovidgoyal/kitty-test:latest
    steps:
        - checkout
        - run: if grep -Inr '\s$' kitty kitty_tests kittens docs *.py *.asciidoc *.rst .gitattributes .gitignore; then echo Trailing whitespace found, aborting.; exit 1; fi
        - run: python3 -m flake8 --count .
        - run: python3 setup.py build --debug --verbose
        - run: python3 test.py
        - run: make FAIL_WARN=-W man
        - run: make FAIL_WARN=-W html
        - run: python3 setup.py linux-package

workflows:
    version: 2
    all_jobs:
        jobs:
            - linux-system-python
