version: 2
jobs:
  linux-system-python:
    docker:
        - image: kovidgoyal/kitty-test:latest
    steps:
        - checkout
        - run: if grep -Inr '\s$' kitty kitty_tests kittens docs *.py *.asciidoc *.rst .gitattributes .gitignore; then echo Trailing whitespace found, aborting.; exit 1; fi
        - run: flake8 --count .
